spring:
  mvc:
    servlet:
      path: /control

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  main:
    banner-mode: off
logging:
  level:
    root: fatal
    com.github.jmgoyesc.control: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - ${LOG_LEVEL_PATTERN:-%5p} --- %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss} - ${LOG_LEVEL_PATTERN:-%5p} --- %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file:
    path: "./logs"
---
spring:
  config:
    activate:
      on-profile: ec2
logging:
  file:
    path: "/home/ec2-user/logs"