spring:
  mvc:
    servlet:
      path: /agent
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  main:
    banner-mode: off
logging:
  level:
    root: fatal
    com.github.jmgoyesc.agent: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%t] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - [%t] - %msg%n"
  file:
    path: "./logs"
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8181
---
spring:
  config:
    activate:
      on-profile: ec2
logging:
  file:
    path: "/home/ec2-user/logs"